### ISSUE TITLE
File entrypoint.sh missing

### ISSUE THREAD

**Issue by robdyck** [OpenSIPS/opensips-ims-ce#3]
I have been looking at integraring open5gs and opensips-ims-ce. I was able to start the containers but immediately after I get and error message.

``
stat /etc/opensips/entrypoint.sh no such file or directory
``

Indeed the file does not exist. Presumably the location and file name were specified in a Dockerfile but no Dockerfile is included with the source code.

My image was pulled not built locally.

**Comment by razvancrainea** [comment]
@robdyck what component is reporting this error?

**Comment by robdyck** [comment]
Going back farther on the output I see
```
icscf      | Jan 29 21:48:55 [1] ERROR:core:parse_opensips_cfg: loading config file /etc/opensips/opensips.cfg: No such file or directory
icscf      | Jan 29 21:48:55 [1] ERROR:core:main: failed to parse config file (null)
icscf      | Jan 29 21:48:55 [1] NOTICE:core:main: Exiting....
sgwu       | Error: Invalid component name: 'sgwu-1'
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/etc/opensips/entrypoint.sh": stat /etc/opensips/entrypoint.sh: no such file or directory: unknown
```
I found time to dig into this more thoroughly. Looking in docker-compose.yml I see
```
icscf:
    image: opensips/opensips:ims-ce
    container_name: icscf
    dns: ${DNS_IP}
    volumes:
      - ./ims_opensips/icscf:/etc/opensips 
      - ./ims_opensips/substenv.sh:/etc/opensips/substenv.sh

```
So it is binding  ./ims_opensips/icscf to the container's :/etc/opensips.
./ims_opensips/icscf does not contain the script entrypoint.sh

```
ls -l ims_opensips/icscf
total 4
drwxr-xr-x 2 root root 4096 Jan 29 21:48 substenv.sh

```
What puzzles me is that the icscf entry in docker--compose.yml does not seem to call that script.
This is unlike pcscf and scscf with this entry.

```
entrypoint: /etc/opensips/entrypoint.sh

```
But apparently it is trying to call it.
